server:
  port: 8980
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: profile

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin